FROM python:slim

RUN apt-get update && apt-get install -y 
RUN apt-get -y install sudo
RUN adduser --disabled-password --gecos '' admin
RUN adduser admin sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER admin

RUN sudo apt-get install gcc -y
RUN pip3 install flask
RUN pip3 install requests
RUN sudo apt-get install libssl-dev -y
RUN sudo apt-get install default-libmysqlclient-dev -y
RUN pip3 install mysqlclient
RUN pip3 install Flask-MySQLdb
COPY ./. ./home/admin/Service_1

RUN sudo chmod 775 ~/Service_1/app.py
WORKDIR /home/admin/Service_1
ENTRYPOINT ["python3", "app.py"]