version: '3.7'

networks:
    cur:
        driver: overlay

services:
    flaskcur:
        build:
            context: ./Service_1
        image: leonct/currency:flaskcur_latest
        container_name: flaskcur
        env_file:
            - ./keys.env
        ports:
            - "5000"
        networks:
            - cur
        #deploy:    
            #mode: global
            #replicas: 2

        
    fiatgen:
        build:
            context: ./Service_2
        image: leonct/currency:fiatgen_latest
        container_name: fiatgen
        networks:
            - cur
        deploy:    
            #mode: global
            replicas: 2

    crypgen:
        build:
            context: ./Service_3
        image: leonct/currency:crypgen_latest
        container_name: crypgen
        networks:
            - cur
        deploy:    
            #mode: global
            replicas: 2
        
    currpair:
        build:
            context: ./Service_4
        image: leonct/currency:currpair_latest
        container_name: currpair
        env_file:
            - ./keys.env
        networks:
            - cur
        deploy:    
            #mode: global
            replicas: 2

    nginxcur:
        build:
            context: ./nginx
        image: leonct/currency:nginxcur_latest
        container_name: nginxcur
        ports: 
            - 80:80
        networks:
            - cur
        depends_on:
            - flaskcur
            - fiatgen
            - crypgen
            - currpair
        restart: on-failure:10
        #deploy:    
            #mode: global
            #replicas: 2
    
    