FROM python:latest

RUN apt-get update && apt-get install -y 
RUN apt-get -y install sudo
RUN adduser --disabled-password --gecos '' admin
RUN adduser admin sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER admin

RUN pip3 install flask
RUN pip3 install requests
COPY ./. /home/admin/Service_2

RUN sudo chmod 775 ~/Service_2/app.py
WORKDIR /home/admin/Service_2
ENTRYPOINT ["python3", "app.py"]