pipeline{
    agent any //to define which node to deploy on - any means to deploy on every server that has been defined , e.g. agent leon, joel etc to deploy on server leon and joel

    stages{
        stage('Development Environment'){ 
            steps{
                sh 'chmod +x ./script/*' //makes everything in script folder executable - makes root/group/user executable
                sh './script/before_installation.sh' //use dot to run something
                sh 'echo "Before Installation Commands Complete"'
                sh 'sleep 2'
                sh './script/docker_install.sh'
                sh 'echo "Docker Jenkins Install Complete"'
                sh 'sleep 1'
                sh './script/ansible_install.sh'
                sh 'echo "Ansible Jenkins Install Complete"'
                sh 'sleep 1'
                sh './script/installation.sh'
                sh 'echo "Installation Commands Complete"'
                sh 'sleep 2'
                sh './script/run.sh'
                sh 'echo "Curstack Swarm Built Successfully"'
                sh 'sleep 2'  
            }
        }

        stage('Testing Environment'){
            steps{
                sh './script/testing.sh'
                sh 'echo "Testing completed Successfully"'
                sh 'sleep 2'
                sh 'echo "Pulling down Development Environment"'
                sh './script/posttest.sh'
                sh 'echo "Development Environment Reset"'
            }
        }

        stage('Deployment Environment'){
            steps{
                sh 'echo "Deploying App...."'
                sh './script/deploy.sh'
                sh 'echo "Files Copied over and Run successfully"'
                sh 'sleep 2'
            }
        }
    }
}